[WIP] Generate static lib instead of reference lib
conda-forge/libmatio-feedstock pull request #19
Opened 2018-04-13 15:03 UTC by massich

Fix #18

2018-04-13 15:03 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2018-04-13 15:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [42, 43]

2018-04-13 15:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2018-04-13 16:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [42]

2018-06-25 17:30 UTC, jakirkham commented on recipe/meta.yaml
> +    - set xx=lib /list libmatio.lib # [win]
The linter is requesting another space before `# [win]`. Would get rid of any trailing whitespace as well.

2018-06-25 17:30 UTC, jakirkham commented
Needs a build number bump.

2018-06-25 17:31 UTC, jakirkham commented
Thoughts @tbeu?

2018-07-06 07:58 UTC, 183amir commented
You need to bump the build number as well.

2018-08-21 10:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2018-08-21 11:17 UTC, 183amir requested changes
Is this a WIP? or is it finished?

2018-08-21 11:17 UTC, 183amir commented on recipe/meta.yaml
> +  number: 1
please rebase on master and change build number to 2.

2018-08-21 11:17 UTC, 183amir commented on recipe/meta.yaml
> +    - set xx=lib /list libmatio.lib  # [win]
What does this line do?

2018-08-21 11:17 UTC, 183amir commented on recipe/bld.bat
> +lib /list %LIBRARY_LIB%\libmatio.lib
What does this line do?

2021-03-25 20:15 UTC, traversaro commented
Given CFEP-18 (https://github.com/conda-forge/cfep/blob/master/cfep-18.md), if someone wants to also package a static variant of `libmatio` it should do so by providing an additional `libmatio-static` output, instead of replacing the existing shared build. If anyone is interested in this, feel free to  open a PR in that direction, thanks!

2021-03-25 20:15 UTC, closed without merging