[MRG] backport hotfix from #92
conda-forge/libmatio-feedstock pull request #20
Opened 2018-08-17 09:52 UTC by massich

This is a hotfix to backport #92 while the changes are not in 1.5.12

2018-08-17 09:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2018-08-17 10:35 UTC, agramfort approved these changes

2018-08-18 16:33 UTC, agramfort commented
@tbeu do you see any objection to merge this?

2018-08-18 18:24 UTC, tbeu commented
Just go ahead.

2018-08-18 19:01 UTC, agramfort commented
I don’t have commit rights

2018-08-18 19:42 UTC, tbeu commented
Me neither.

2018-08-18 19:46 UTC, agramfort commented
arfff. I guess we need to wait for @183amir

2018-08-18 20:47 UTC, 183amir requested changes

2018-08-18 20:47 UTC, 183amir commented on recipe/meta.yaml
>    number: 0
Please change the build number to 1 too

2018-08-18 20:47 UTC, 183amir commented
@conda-forge-admin please rerender

2018-08-18 20:49 UTC, 183amir commented
@conda-forge-admin, please rerender

2018-08-18 20:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but it appears we have a merge conflict.
Please try to merge or rebase with the base branch to resolve this conflict.

Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2018-08-21 10:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2018-08-21 10:04 UTC, 183amir commented
@conda-forge-admin, please rerender

2018-08-21 11:14 UTC, 183amir approved these changes

2018-08-21 11:14 UTC, merged

2018-08-21 11:15 UTC, 183amir commented
Thank you.